apiVersion: apps/v1
kind: Deployment
metadata:
  name: hw-deployment
spec:
  replicas: 2

  # Tells Kubernetes which Pods this Deployment manages
  selector:
    matchLabels:
      app: hello-world

  # Template for each Pod created by the Deployment
  template:
    metadata:
      labels:
        app: hello-world  # This label must match the selector above
    spec:
      containers:
        # First container: Your application
        - name: hw-container
          image: synapsenet/hello_world:latest
          ports:
            - containerPort: 5000

        # Second container: Nginx
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80